<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI [
    <!ELEMENT TEI (header, facsimile?, testo+)>

    <!ELEMENT header (#PCDATA)>
    <!ATTLIST header
        type CDATA #FIXED "intestazione"
        lang NMTOKEN #IMPLIED
    >

    <!ELEMENT facsimile (#PCDATA)>
    <!ATTLIST facsimile
        source CDATA #REQUIRED
        ref IDREFS #IMPLIED
    >

    <!ELEMENT testo (#PCDATA | seg)*>
    <!ATTLIST testo
        id ID #REQUIRED
        type CDATA #IMPLIED
    >

    <!ELEMENT seg (#PCDATA)>
]>
<TEI>
    <header type="intestazione" lang="it">Intestazione del documento</header>
    <facsimile source="img001.jpg" ref="fig1 fig2">Facsimile</facsimile>
    <testo id="t1" type="narrativo">Esempio di <seg>segmento</seg> di testo.</testo>
</TEI>
